apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-db
  namespace: {{ .Values.namespace }}
  labels:
    app: post-db
spec:
  selector:
    matchLabels:
      app: post-db
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  template:
    metadata:
      labels:
        app: post-db
    spec:
      containers:
        - name: post-mongo-container
          image: mongo:latest
          ports:
            - containerPort: 27017
              name: post-db
          livenessProbe:
            {{- toYaml $.Values.db.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml $.Values.db.readinessProbe | nindent 12 }}
          envFrom:
            - configMapRef:
                name: post-db-config
            - secretRef:
                name: post-db-secret
