apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-srv
  namespace: {{ .Values.namespace }}
  labels:
    app: post-srv
spec:
  selector:
    matchLabels:
      app: post-srv
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  template:
    metadata:
      labels:
        app: post-srv
    spec:
      containers:
        - name: post-srv-container
          image: liakhaliaksandr/post-srv:1.0.0
          ports:
            - containerPort: 8080
              name: post-srv
          livenessProbe:
            {{- toYaml $.Values.srv.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml $.Values.srv.readinessProbe | nindent 12 }}
          envFrom:
            - configMapRef:
                name: post-srv-config
            - secretRef:
                name: post-srv-secret
